spring.application.name=song

# PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# Let Spring Boot auto-detect the best settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Force SSL for Neon
spring.datasource.hikari.connection-timeout=30000