spring.application.name=song

# Auto-config will pick up the URL from Render's Environment Variables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# This tells Hibernate exactly what language to speak since it's struggling to auto-detect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect